defaultEntryPoints = ["http"]

[entryPoints]
  [entryPoints.http]
  address = ":5001"

  [entryPoints.ws]
  address = ":5005"

  [entryPoints.dashboard]
  address = ":15001"

[api]
entryPoint = "dashboard"
dashboard = true

[consulCatalog]
